[package]
name = "aoc"
version = "0.1.0"
authors = ["Jezza <jezzadabomb@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.0.27", features = ["derive", "env"] }
structopt = "0.3.25"
anyhow = "1.0.51"
toml_edit = "0.10.0"
parse-display = "0.5.3"