[package]
name = "commons"
version = "0.1.0"
authors = ["Jezza <jezzadabomb@gmail.com>"]
edition = "2021"

[dependencies]
itertools = { version = "0.10", optional = true }
num-integer = { version = "0.1", optional = true }